### ISSUE TITLE
Support gesture navigation on Android 10+

### ISSUE THREAD

**Issue by finxol** [finnmglas/Launcher#95]
**Is your feature request related to a problem? Please describe.**

I can't use gesture navigation on Android 10 with this launcher.

**Describe the solution you'd like**

It would be useful to support gesture navigation 

**Describe alternatives you've considered**

Haven't been able to come up with any.

**Additional info**

Android settings says Launcher doesn't support gesture navigation, so I can't activate it when Launcher is my default launcher.
I'd totally use it if it were supported.

**Comment by Kj-is-escape** [comment]
Every third party launcher has the same problem, because it's an issue with Android 10, the Nova Launcher website [explains it very well](https://help.teslacoilapps.com/faq/gesture-navigation). It is already solved in Android 11 and it works well (at least on my phone) so if an update is available for your device just upgrade to Android 11 and it will be fixed.

**Comment by finxol** [comment]
Oh right. Thanks for the reply. I'll wait for an Android update then :)
